### PR TITLE
fix(autodevops): dont run test+lint on tags

### PR DESCRIPTION
**Pull request by revolunet**
save a few minutes

### CODE REVIEW

**Review by douglasduteil — COMMENTED** [review]
Do we have a problem with lint and test on tags ?

**Comment by douglasduteil** [comment]
I see no issues on https://gitlab.factory.social.gouv.fr/SocialGouv/gitlab-ci-yml/-/pipelines/81257 nor https://gitlab.factory.social.gouv.fr/SocialGouv/gitlab-ci-yml/-/pipelines/81257

**Comment by revolunet** [comment]
yep, no issue but is it necessary ?

**Comment by douglasduteil** [comment]
Maybe no...

**Pull request merged**
