### PR TITLE
feat(autodevops): make lint and test jobs optional

### PR DESCRIPTION
**Pull request by revolunet**
as per gitlab : https://docs.gitlab.com/ee/topics/autodevops/#disable-jobs

### CODE REVIEW

**Comment by douglasduteil** [comment]
I'm not a fan of this :smirk:
I'm not sure it's a use case we want to propose as having a linted and tested code is a minimum for me

**Comment by revolunet** [comment]
when i iterate on my CI i dont want to lint/test :)

**Comment by douglasduteil** [comment]
hum... 
You iterate on your CI with the autodevops ?
It's for a scenario where you want to change how the autodevops works ?
I don't like it but if it's legit for you add some docs in the README and we merge this :+1:

**Comment by revolunet** [comment]
yep when trying to setup migrations, playing with helm or whatever this can save some nerves :)

**Comment by revolunet** [comment]
added some doc

**Comment by revolunet** [comment]
thanks !

**Pull request merged**
