### PR TITLE
feat: Switch from Docker to Kaniko based on pipeline env variable: AUTO_DEVOPS_KANIKO.

### PR DESCRIPTION
**Pull request by gary-van-woerkens**
BREAKING CHANGE: The file `base_kaniko_stage.yml` no longer exists.

### CODE REVIEW

**Comment by revolunet** [comment]
LGTM

**Review by douglasduteil — APPROVED** [review]

**Review by douglasduteil — COMMENTED** [review]
🆙  de la doc.
ça te va @gary-van-woerkens ?

**Comment by gary-van-woerkens** [comment]
> 🆙 de la doc.
> ça te va @gary-van-woerkens ?

Yes, perfect!

**Pull request merged**
